name: BedWarsX
version: '${project.version}'
main: net.alterrastudios.bedwars.BedWars
api-version: '1.16'
authors: [MrFil_27]
description: A bedwars plugin
commands:
  setup-bedwars:
    usage: /<command>
    description: "Setup a bedwars"
  start-bedwars:
    usage: /<command>
    description: "Start a bedwars"
